### ISSUE TITLE
.19.2006 (or other recent version) broke this mod

### ISSUE THREAD

**Issue by TSM-EVO** [DingoDjango/NoForcedSlowdown#7]
There was some breaking changes made in the recent update and a lot of mods are broken, this one included.

**Comment by DingoDjango** [comment]
Known bug. The code I was patching got inlined, basically happens randomly sometimes when they compile RimWorld in a new version and the code sees a "neat trick" it can do.

It will take some free time that I don't have right now to figure out what to do about that.
